### ISSUE TITLE
CSP Night at the Museum 6-9pm

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/teacher_portfolio#108]
### Capture the moment
Provide a link to your Blog containing the following

- Blog / article on you and team
  - reflection on glows/grows from your demo, 
  - from feedback, something you will add to individual CPT project
  - visuals or pics of team and people you talked

- Blog on event
  - something you saw in CompSci that impressed
  - something you saw outside of CompSci that you liked

**Comment by BearytheGreenBear** [comment]
Kyle Liang
Lopez P1
[Link to Blog](https://bearythegreenbear.github.io/csp-blog/2024/02/16/night-at-the-museum-reflection.html)

**Comment by Akhil353** [comment]
Akhil Singamneni
Period 1 Mr. Lopez
[N@M Blog Post](https://akhil353.github.io/student//2024/02/16/N@M-Blog.html)

**Comment by anikabhatnagar20** [comment]
Anika Bhatnagar 
Period 2 
[Capture the Moment](https://anikabhatnagar20.github.io/anikabhatnagar20//2024/02/15/Capturethemomment_IPYNB_2_.html)

**Comment by DavidL0914** [comment]
David Lee
Period 2
[N@TM Review!!](https://davidl0914.github.io/student//2024/02/16/N@TM.html)

**Comment by SGTech08** [comment]
Saathvik Gampa
Period 1 Mr. Lopez
[N@M Blog](https://sgtech08.github.io/student/2024/02/16/nightatthemusuem.html)

**Comment by 7mwang** [comment]
Matthew Wang
Period 2
[N@TM Reflection](https://7mwang.github.io/matthew-wang/2024/02/16/natmreflect.html)

**Comment by LincolnC2008** [comment]
Lincoln Crowell
Period 2 Mr. Mortensen
Blog: https://lincolnc2008.github.io/student3//2024/02/16/N@TM-reflection.html

**Comment by nitinsandiego** [comment]
Nitin Balaji
Period 2 CSP
Blog: [Link to my blog](https://nitinsandiego.github.io/student//2024/02/16/Night-At-the-Museum.html)

**Comment by VanceReynolds** [comment]
Vance Reynolds
Period 2 Mr. Mortenson
[N@TM Blog](https://vancereynolds.github.io/cspblog2//2024/02/16/NightAtTheMuseum.html)

**Comment by tuckergol** [comment]
Tucker Golpariani
Period 2
[N@tM Reflection Blog](https://tuckergol.github.io/student2//2024/02/15/N@tM_Reflection_IPYNB_2_.html)

**Comment by peytonl11098** [comment]
Peyton Leigh
Period 2
[N@tM Blog Post](https://peytonl11098.github.io/Ultron/2024/02/15/NATM_IPYNB_2_.html)

**Comment by iKAN2025** [comment]
Isabel Marilla
Period 2
https://ikan2025.github.io/Nighthawk-Pages//2023/08/16/NightAtTheMuseum.html

**Comment by DanteA-tech** [comment]
N@TM review
Dante Atanassov
Period 2 Mort
[link to blog](https://dantea-tech.github.io/student/2024/02/16/N@TM-Blog.html)

**Comment by sergi1207** [comment]
Sergi Serpukhovitinov
Period 2 
CSP
[Link to Blog](https://jm1021.github.io/sergiStudent//2024/02/16/Final-museum-blog.html)

**Comment by M8tth3** [comment]
Matthew Wakayama
Period 2
CSP
[Blog](https://m8tth3.github.io/m8th3_2.0//2023/02/16/Night.html)

**Comment by nikkihekmat** [comment]
Nikki Hekmat
Period 4 Lopez
CSP
[Link to Blog](http://127.0.0.1:4100/nikki-2.0/2024/02/16/N@M.html)

**Comment by eunseolim123** [comment]
Eunseo Lim
Period 4 Lopez
CSP
[Link to Blog](https://eunseolim123.github.io/student-2.0/2024/02/16/N@TM_IPYNB_2_.html)

**Comment by srivaidyas** [comment]
Sri Vaidyanathan S
Period 4 Lopez
CSP
[Link to Blog](https://srivaidyas.github.io/student2.0//2024/02/16/N@TMREview_IPYNB_2_.html)

**Comment by jntpham** [comment]
Jordan Pham
Period 4 Lopez
CSP
[Link to Blog](https://jntpham.github.io/jphamblog/csp)

**Comment by pranavivak** [comment]
Pranavi Vakkala
Period 5 Lopez
CSP
[Link to Blog](https://github.com/pranavivak/student2/blob/63248dffff53c8a0961cbedb242e0ea7b3987722/_posts/2023-02-16-Nightatthemuseumreviewticket.md)

**Comment by Tanvi-3** [comment]
Tanvi Pampati
Period 5 Lopez
CSP
[link to blog](https://github.com/Tanvi-3/tanvipampati3/blob/bf0acbffb4d6c837e491afe1b1b97b4da5eef22d/_posts/2024-02-16-NATM2.md)

**Comment by YeongsuKimm** [comment]
Yeongsu Kim 
Period 5 Lopez
CSP
[NATM Reflection](https://yeongsukimm.github.io/yeongsuk//2024/02/16/NATM_IPYNB_2_.html)

**Comment by JasonGao76** [comment]
Jason Gao
Period 5 Lopez
CSP
[Link to Blog Reflection](https://jasongao76.github.io/students//2024/02/16/N@TMReflection.html)

**Comment by spooketti** [comment]
Jonathan Liu
Period 5 Lopez
CSP
<a href="https://spooketti.github.io/studentmodern//2024/02/16/NATM2024.html">Link to Blog</a>

**Comment by Lin-cT** [comment]
Lindsay Tang
Period 5 Lopez
CSP
[Blog](https://github.com/Lin-cT/stu2/blob/main/_notebooks/2024-02-16-N%40tM_Reflection.ipynb)

**Comment by SriS126** [comment]
Sri Surapaneni
P5 Lopez
[Blog](https://sris126.github.io/student//2024/02/16/N@MBlog_IPYNB_2_.html)

**Comment by KinetekEnergy** [comment]
Aashray Reddy
P5 Lopez
CSP
https://kinetekenergy.github.io/blog/posts/Natm_IPYNB_2_/

**Comment by RonitT1234** [comment]
Ronit Thomas
Period 1 Mr.Lopez
[Link](https://ronitt1234.github.io/CSP_BLOG_RT//2024/02/15/individual-tri-two.html)

**Comment by ninaadkiran** [comment]
Ninaad Kiran
P4 Lopez
CSP
Link to [Issue](https://github.com/ninaadkiran/group-frontend/issues/1) (Something is wrong with my website)

**Comment by devaSas1** [comment]
Deva Sasikumar
Period 5 Lopez
CSP
https://devasas1.github.io/student//2024/02/16/N@TMTri2Reflection_IPYNB_2_.html

**Comment by AdiBricks** [comment]
Aditya Ramesh
Period 5 Lopez
CSP
https://adibricks.github.io/student//2024-02-15-NATMTri2Blog.ipynb

**Comment by vibha-yganji** [comment]
Vibha Ganji
Period 2 Mortensen
CSP
[Link to Blog Post](https://vibha-yganji.github.io/student-vibha/2024/02/15/natm-reflection_IPYNB_2_.html)

**Comment by Gurbop** [comment]
Gurshawn B
Period 2 CSP
https://gurbop.github.io/CSPBlog2//2024/02/16/natmrefl.html

**Comment by ad1tyad3sa1** [comment]
Aditya Desai
Period 2 Mortensen 
CSP
https://github.com/ad1tyad3sa1/adityadesai2.0/blob/main/_posts/2024-02-16-NATM_blog.md

**Comment by varunm532** [comment]
Varun Manoj Pillai
Period 2 CSP
https://varunm532.github.io/varun2//2024/02/02/N@TM.html

**Comment by alaraipek** [comment]
Alara Ipek
Period 2
CSP
[N@TM Blog](https://alaraipek.github.io/student//2024/02/16/NATM.html)

**Comment by hanlunli** [comment]
Hanlun Li
Period 2 Mortenson
CSP
https://hanlunli.github.io/student/NightAtTheMuseum
(turn off dark mode, its really buggy)

**Comment by jplip** [comment]
Justin Liporada
Period 2
CSP
[N@TM Blog](https://jplip.github.io/justin2.0//2024/02/16/N@TM.html)

**Comment by ArnavNadar** [comment]
Arnav Nadar 
Period 2 CSP 
[N@TM Review](https://arnavnadar.github.io/student2/2024/02/16/N@TM_Review.html)

**Comment by Th35py27** [comment]
Nandan Vallamkondu
P2 CSP
https://th35py27.github.io/CSP//2024/02/16/N@tm_IPYNB_2_.html

**Comment by ak146** [comment]
Andrew 
P2 csp
[blog](https://ak146.github.io/FunnyBlog2.0/2024/02/14/new_post_IPYNB_2_.html)

**Comment by dino596** [comment]
Arthur Liu
P4 CSP
https://dino596.github.io/t2csp//2024/02/16/Night_at_the_Museum_Review_IPYNB_2_.html

**Comment by tarunja1ks** [comment]
Tarun Jaikumar
Period 5 CSP
[Blog](https://tarunja1ks.github.io/student/2024/02/16/NATMREFLECTION.html)

**Comment by SrijDude3416** [comment]
Srijan Atti
Period 5 CSP
[Blog](https://srijdude3416.github.io/student/2024/02/16/NATM-Reflection.html)

**Comment by AkshayNagesh** [comment]
Akshay Nagesh
P2 CSP
[N@TM blog](https://github.com/IshanCornick/Real-Estate-Frontend/issues/5#issue-2139857542)

**Comment by IshanCornick** [comment]
Ishan Cornick
Period 2 Mr Mortensen
CSP
[Blog](https://ishancornick.github.io/new_student/2024/02/16/N@TM.html)

Comment are not working for me, tried fixing with 3 different ways and didn't work.

**Comment by Imaad08** [comment]
Imaad Muzaffer
Period 2 Lopez
[Blog](https://imaad08.github.io/student2/natm)

**Comment by will-w-cheng** [comment]
William Cheng
Period 5 CSP Lopez
[Blog](https://will-w-cheng.github.io/student-public//2024/02/15/NATM_IPYNB_2_.html)

**Comment by trevorhuang1** [comment]
Trevor Huang
Period 2 CSP
<a href="https://trevorhuang1.github.io/csp_blog/natm">N@TM Review</a>

**Comment by advikg** [comment]
Advik Garg
P5 CSP
[N@TM Blog](https://advikg.github.io/student/2024/02/16/natm-checkpoint.html)

**Comment by tarasehdave** [comment]
Tara Sehdave
p2
[N@TM BLOG](https://tarasehdave.github.io//c4.1/2024/02/15/N@TM2_IPYNB_2_.html)

**Comment by AidanLau10** [comment]
Aidan Lau
P1
[N@TM Blog](https://aidanlau10.github.io/student2//2024/02/15/n@tm_IPYNB_2_.html)

**Comment by AnvayYadav** [comment]
Anvay Yadav
Period 1
[Night at the museum blog](https://anvayyadav.github.io/student//2024/02/17/Night-at-the-museum-review.html)

**Comment by Ashwinv93** [comment]
Ashwin Visvanath
Period 2
[Night at the Museum Blog](https://ashwinv93.github.io/CompSci//2024/02/17/N@TM-Blog.html)

**Comment by EthanH06** [comment]
Ethan Hong
Period 4 
[https://[raw.githubusercontent.com/EthanH06/EthanT2/main/_notebooks/2024-02-16-N%40TM.ipynb](Issue)](url)

**Comment by alishahussain** [comment]
Alisha Hussain
Period 2 Mortensen
(blog)[https://alishahussain.github.io/student2//2024/02/16/nightatmuseum.html]

**Comment by MEERIE** [comment]
Ameer Hussain
Period 2
Mortensen
[link to blog](https://meerie.github.io/stew2//2024/02/18/N@TM_Blog.html)

**Comment by Tanuj253** [comment]
Tanujsai Nimmagadda
period 2 Mortensen
[N@TM Blog](https://github.com/IshanCornick/Real-Estate-Frontend/issues/6)

**Comment by monke7769** [comment]
Hayden Chen
P5 Lopez
[NatM Blog](https://monke7769.github.io/copy1//2024/02/23/NatM_Reflection_IPYNB_2_.html)

So sorry for being late, I was absent last Friday

**Comment by AdityaSamavedam** [comment]
Aditya Samavedam
P5 Lopez
[N@tM Blog](https://adityasamavedam.github.io/student2//2024/02/22/N@tM-blog.html)

**Comment by samhita-l** [comment]
Samhita Lagisetti
P5 Lopez
[N@TM Reflection](https://samhita-l.github.io/compsci/2024/02/23/N@TM_Tri2.html)

**Comment by sharonkodali** [comment]
Sharon Kodali 
P2 Mortenson
[N@TM Blog](https://sharonkodali.github.io/sharonk//2024/02/20/natmblog_IPYNB_2_.html)

**Comment by lakshusan** [comment]
Lakshanya Sankaran
P2 Mortensen
[N@TM Blog](http://127.0.0.1:4200/student2//2024/02/16/N@TM-blog.html)

**Comment by Deeskili** [comment]
Cayden Shi 
Period 4 Lopez 
[N@TM Blog](https://deeskili.github.io/student2.0//2024/02/24/NATMReflection.html)

**Comment by SrinivasNampalli** [comment]
Srinivas Nampalli 
Period 1 Lopez
[https://github.com/SrinivasNampalli/NewStudent/issues/7](url)

**Comment by JBaza12** [comment]
Jared Baza
Period 4 Lopez
https://jbaza12.github.io/JaredsBlog//2024/02/21/NATMBlog_IPYNB_2_.html

**Comment by Djxnxnx** [comment]
Tarun Tata
Period 1 Lopez
[N@TM Blog](https://djxnxnx.github.io/student/5.a/c4.1/2024/02/25/NATMWriteUp.html)

**Comment by aashrayr** [comment]
Aashray Rajagopalan
Period 1
Mr Lopez

https://aashrayr.github.io/student2/2024/02/25/NATM.html

**Comment by AidanDelgado2** [comment]
Aidan Delgado
Period 4 Lopez
[N@TM Blog](https://aidandelgado2.github.io/student2//2024/02/25/N@TM_Reflection.html)

**Comment by KaydenLe** [comment]
Kayden Le
Period 2 Mortensen
[Blog](https://kaydenle.github.io/kaydentri2//2024/02/16/CPT_Blog_IPYNB_2_.html)

**Comment by tanav-kambhampati** [comment]
Tanav Kambhampati
Period 1 Lopez
![Blog](https://tanav-kambhampati.github.io/student2//2024/02/26/N@TM_IPYNB_2_.html)

**Comment by jaydenchen17** [comment]
Jayden Chen
Period 1 Lopez
[Blog](https://jaydenchen17.github.io/csp//N@TM2)

**Comment by KaiyuSugiyama** [comment]
Kaiyu Sugiyama
Period 4 Lopez 
[Blog](http://127.0.0.1:4200/student//2024/02/25/N@TM_IPYNB_2_.html)

**Comment by brandonso36** [comment]
Brandon So
Period 1 Lopez
[Blog](https://brandonso36.github.io/brandonso//c4.1/2024/02/26/T2-N@tM_IPYNB_2_.html)

**Comment by MiguelVilla1** [comment]
Miguel Villa Hernandez
P1 Lopez
[Link to issue](https://github.com/MiguelVilla1/stewie/issues/3)

**Comment by AustinZhang1** [comment]
Austin Zhang
P4 Lopez
[Blog](https://github.com/AustinZhang1/student/blob/main/_notebooks/2024-2-16-N%40TMREview.ipynb)

**Comment by Saaras859** [comment]
Saaras Kodali
P4 LOPEZ
[blog](https://docs.google.com/document/d/16FYaDR6uQqspUFf5yaqCAVRmZXDKgntjBBU1yWhQ9Ao/edit)

**Comment by Aditi99b** [comment]
Aditi Bharadwaj, Eshika Pallapotu, Avanthika Daita, Cindy Liang, Nupur Bhalla
Period 5 Lopez
[Group Issue Link ](https://github.com/EshikaP1/2front/issues/1)
