### ISSUE TITLE
CSA Checkpoint Night at the Museum 6-9pm

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/teacher_portfolio#109]
### Capture the moment
Provide a link to your Blog containing the following

- Two Trimester focus planning
  - how you used N@tM to capture test data to be used in trimester 3
  - from feedback, something you will add to your project
  - other?

- Blog / article on you and team
  - reflection on glows/grows from your demo/presentations
  - visuals or pics of team and people you talked

- Blog on event
  - something you saw in CompSci that impressed
  - something you saw outside of CompSci that you liked

**Comment by Emaad-Mir** [comment]
[Emaad Mir's N@TM Blog](https://emaad-mir.github.io/emaad-github-pages1/c1.4/2024/02/16/Capture-The-Moment-Blog.html)

**Comment by vivianknee** [comment]
Grace Wnag, Aliya Tang, Vivian Ni, Emma Shen
[Link](https://vivianknee.github.io/vivianblog/posts/Tri2-n@tm/) to Blog

**Comment by drewreed2005** [comment]
Name: Drew Reed
Period 1
[Link to blog](https://drewreed2005.github.io/dre2.0//2024/02/15/N@tM_Tri_2.html)
[Link to group issue from N@tM with live feedback notes](https://github.com/John-sCC/jcc_frontend/issues/42)

**Comment by JishnuS420** [comment]
Name: Jishnu Singiresu
Period 1 
[Link to Blog](https://jishnus420.github.io/BlogCSA/2024/02/15/NATM.html)

**Comment by Pitsco** [comment]
Name: Derrick Huang
Period 1
[Link to Blog](https://pitsco.github.io/personal/c4.0/2024/02/16/N@TM-blog.html)

**Comment by kaiden-dough** [comment]
Name: Kaiden Do
Period 1
[Link To Blog](https://kaiden-dough.github.io/kaidencsablog//2024/02/16/natmfeb.html)

**Comment by TheoH32** [comment]
Theo Huntalas
Period 1
[Blog](https://github.com/Codemaxxers/Issues/issues/38)

**Comment by YLu-1258** [comment]
Alexander Lu
Period 1
[Blog](https://ylu-1258.github.io/YLU_blog/posts/MuseumReflection/)

**Comment by Jyustin** [comment]
Name: Justin Nguyen
Period 1
[Blog](https://jyustin.github.io/JN-CSAblog//2024/02/16/NATM2.html)

**Comment by realethantran** [comment]
Ethan Tran
Period 1
[Link to Blog](https://ethan.nighthawkcodingsociety.com/2024/02/16/night-at-museum_IPYNB_2_.html)

**Comment by Ryanrob327** [comment]
Ryan McWeeny
Per 1
[Link](https://github.com/Ryanrob327/CSA/issues/5)

**Comment by VishnuAravind12** [comment]
Vishnu Aravind
Period 1
Blog [Link](https://vishnuaravind12.github.io/vishnu/2024/02/16/Capture_The_Moment.html)

**Comment by vardaansinha** [comment]
Vardaan Sinha
Period 1
[Blog](https://vardaansinha.github.io/vsstudent//2024/02/16/natmtri2.html)

**Comment by DasMoge124** [comment]
Name: Kevin Du
Period 1:
(Link)[https://github.com/RIK-CSA/RIK-CSA-frontend/issues/15]

**Comment by nikhilc3** [comment]
Nikhil Chakravarthula
Period 1
[Blog](https://nikhilc3.github.io/csa//2024/01/16/Night@Musuem_IPYNB_2_.html)

**Comment by raunak2007** [comment]
Raunak Mondal
Period 1
[Link](https://raunak2007.github.io/csa-pages/2024/02/15/blog.html)

**Comment by sreejagangapuram** [comment]
Sreeja Gangapuram
Period 1 
[Link to Blog](https://github.com/sreejagangapuram/sreejagangg/blob/main/_notebooks/2024-02-16-niteblogy.ipynb)

**Comment by Tirth-Thakkar** [comment]
Tirth Thakkar

[Blog](https://tirth-thakkar.github.io/Mort-Pages-Personal/week33/2024/02/16/NATMT2_IPYNB_2_.html)

**Comment by isabelle926** [comment]
Isabelle Gunawan
Period 1
[Blog](https://github.com/isabelle926/CSA_tri1_student/issues/3)

**Comment by aidenhuynh** [comment]
Aiden Huynh
Period 3
[Link](https://aidenhuynh.github.io/Epic_CSA/2024/02/16/Natm_Review.html)

**Comment by EdwinKuttappi** [comment]
Edwin Abraham
Period 3
Link

**Comment by lunaiwa** [comment]
Luna Iwazaki
Period 3
[Blog](https://github.com/lunaiwa/student-template/issues/21)

**Comment by raymondYsheng** [comment]
Raymond Sheng
Period 3
[Blog](https://raymondysheng.github.io/CSA_Repo/2024/02/16/N@TM-Tri-2_IPYNB_2_.html)

**Comment by nVarap** [comment]
Varaprasad Nibhanupudi
Period 3
[Blog](https://nvarap.github.io/CSABlog/2024/02/16/NATMTri2.html)

**Comment by Firestorm0986** [comment]
Aditya Nawandhar
Period 3 
[blog](https://firestorm0986.github.io/CSA-blog-site//2024/02/16/NM-Second-tri_IPYNB_2_.html)

**Comment by hsinaDitaM** [comment]
Mati Danish
Period 3
[blog](https://hsinaditam.github.io/CSA_Notes/2024/02/16/capture-the-moment_IPYNB_2_.html)

**Comment by rachit-j** [comment]
Rachit Jaiswal
Period 3
[Link to Blog](https://github.com/rachit-j/Rackets-Blog/issues/5)

**Comment by Toby-Leeder** [comment]
Toby Leeder
Period 3
[Link](https://toby-leeder.github.io/CSABlog//2024/02/16/N@tM-Review.html)

**Comment by tanayp327** [comment]
Tanay Patel
Period 3
[Link](https://tanayp327.github.io/bloggy/2024/02/15/CSA_checkpoint.html)

**Comment by Henerystone** [comment]
Shreyas Sarurkar
Period 3
[link](https://henerystone.github.io/repo//2024/01/17/Individual_review.html)

**Comment by AniCricKet** [comment]
Aniket Chakradeo
Period 3
[Blog](https://anicricket.github.io/musical-guacamole/natm2)

**Comment by paravsalaniwal** [comment]
Parav Salaniwal
Period 3
[Blog](https://paravsalaniwal.github.io/praopersonal/natmblogt2)

**Comment by VINERAJ** [comment]
Vinay Rajagopalan
Period 3
[Blog](https://vineraj.github.io/CSAblog2.0/2024/02/16/NATM-Reflection_IPYNB_2_.html)

**Comment by Soham360** [comment]
Soham Kamat
Period 3
[Link](https://soham360.github.io/APCSA/2024/02/16/Night-At-The-Museum.html)

**Comment by tanishapatil1234** [comment]
Tanisha Patil 
Period 3 
[Link](https://tanishapatil1234.github.io/tri2/natm)

**Comment by STG-7** [comment]
Shaurya Goel
Period 3
[Issue Link](https://stg-7.github.io/CSABlogging//2024/02/16/NATMblog.html)

**Comment by rohinsood** [comment]
Rohin Sood
Period 3
[Link](https://rohinsood.github.io/csa/2024/02/16/tri-2-NATM.html)

**Comment by Krishiv111** [comment]
Krishiv Mahendru
Period 3
[Link](https://krishiv111.github.io/liverpoolkm3/2024/02/16/NATMtri2blog.html)

**Comment by Jw95z** [comment]
James Lee
Period 3
[Link](https://jw95z.github.io/CSA/capturethemoment)

**Comment by DavidVasilev1** [comment]
David Vasilev
Period 1
[Link](https://davidvasilev1.github.io/CSAsite/posts/N@TM-tri2/)

**Comment by PaarasPurohit** [comment]
| | |
| --- | --- |
| Name | Paaras Purohit |
| Period | 3 |
| Link | [N@TM CSA Checkpoint](https://men-in-brown.github.io/BrownPages/natm-retro) |

**Comment by BobTheFarmer** [comment]
Colin Weis 
Period 3 
Link

**Comment by aliyatang** [comment]
Aliya Tang
Period 1
[Link](https://aliyatang.github.io/aliyaBlog/posts/tri2natm/)

**Comment by Ant11234** [comment]
Anthony Bazhenov
Period 1
[Blog](https://ant11234.github.io/student/2024/02/16/N@TMBlogs_IPYNB_2_.html)

**Comment by JasoXDDD** [comment]
Haoxuan Tong
Period 3
[blog](https://github.com/JasoXDDD/APCSA/blob/main/_notebooks/2024-02-16-NaTM.ipynb)

**Comment by h4seeb-cmd** [comment]
Mirza Beg 
Period 1
[Blog](https://h4seeb-cmd.github.io/CSA-BLOG/2024/02/16/NATMreflection.html)

**Comment by e-shen2022** [comment]
Emma Shen 
Period 1 
Blog

**Comment by dolphinalt** [comment]
Ethan Zhao
Period 1
[Blog](https://github.com/dolphinalt/APCSA-Pages/issues/13)

**Comment by gwang1224** [comment]
Grace Wang
Period 1
[Blog](https://gwang1224.github.io/Graces-Blog/2024/02/24/tri2natm.html)
