### ISSUE TITLE
Deployment Quiz

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/teacher_portfolio#110]
[Instructions[(https://rift24.github.io/RIFT-Frontend/)

**Comment by Emaad-Mir** [comment]
[Emaad's Deployment Quiz](https://github.com/Emaad-Mir/emaad-github-pages1/issues/10#issue-2130609995)

**Comment by EdwinKuttappi** [comment]
[Edwin Abraham](https://github.com/EdwinKuttappi/CSABlog/issues/10)

**Comment by realethantran** [comment]
Ethan Tran
Period 1

[Link to Deployment Quiz](https://github.com/realethantran/ethanBlog/issues/1)

**Comment by PaarasPurohit** [comment]
[Paaras Purohit - Deployment Quiz](https://github.com/PaarasPurohit/apcsa-blog-2.0/issues/6)

**Comment by Soham360** [comment]
Soham Kamat
Period 3

[Link to Deployment Quiz](https://github.com/Soham360/quizbackend/issues/1)

**Comment by AniCricKet** [comment]
Aniket Chakradeo 
Period 3 
[Deployment Quiz](https://github.com/AniCricKet/musical-guacamole/issues/10)

**Comment by nVarap** [comment]
Varaprasad Nibhanupudi
Period 3
[Deployment Quiz Issue](https://github.com/nVarap/CSABlog/issues/15#issue-2130867569)

**Comment by isabelle926** [comment]
Isabelle Gunawan
Period 1
[Issue](https://github.com/isabelle926/CSA_tri1_student/issues/2)

**Comment by aidenhuynh** [comment]
Aiden Huynh
Period 3
[Issue](https://github.com/aidenhuynh/Epic_CSA/issues/2)

**Comment by TayKimmy** [comment]
Tay Kim
Period 1
[Issue Link](https://github.com/TayKimmy/CSA-Repository/issues/10)

**Comment by DavidVasilev1** [comment]
David Vasilev
Period 1
[Issue Link](https://github.com/DavidVasilev1/CSAsite/issues/8#issue-2130603919)

**Comment by YLu-1258** [comment]
Alexander Lu
Period 1
[Deployment Quiz](https://github.com/YLu-1258/YLU_blog/issues/7)

**Comment by DasMoge124** [comment]
Kevin Du
Period 1
[Link](https://github.com/RIK-CSA/RIK-CSA-frontend/issues/14)

**Comment by dolphinalt** [comment]
Ethan Zhao
Period 1
[Link](https://github.com/dolphinalt/APCSA-Pages/issues/11)

**Comment by Orlando-c** [comment]
Orlando Carcamo
Period 3
[Issue Link](https://github.com/Orlando-c/Orlando-Orlando-c/issues/1)

**Comment by tanishapatil1234** [comment]
Tanisha Patil 
Period 3 
Score Received : 3/3
[Link](https://github.com/tanishapatil1234/tri2/issues/5)

**Comment by STG-7** [comment]
Shaurya Goel
Period 3
Score Received: 3/3
[Issue Link](https://github.com/STG-7/CSABlogging/issues/7)

**Comment by JasoXDDD** [comment]
Haoxuan Tong
Period 3
[issue](https://github.com/JasoXDDD/APCSA/issues/12)

**Comment by Ryanrob327** [comment]
Ryan McWeeny
Per 1
2.8/2.0
[issue](https://github.com/Ryanrob327/CSA/issues/4#issue-2134973149)

**Comment by raunak2007** [comment]
Raunak Mondal
Period 1
Score: 2.8/3.0
[Issue](https://github.com/raunak2007/csa-pages/issues/11)
