### ISSUE TITLE
2015 CB MCQ

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/teacher_portfolio#55]
To submit ...

Add your Period, Name, Score, and Blog link (screen shot of score with name in blog).

**Comment by Ryanrob327** [comment]
Per. 1 
Ryan McWeeny

[Link to blog](https://ryanrob327.github.io/CSA//2023/12/21/2015-Practice-Exam-MCQ.html)

**Comment by Ekamjot-Kaire** [comment]
Period 1
Ekam Kaire
32/39

Screenshot with name:

<img width="1055" alt="Screen Shot 2023-12-22 at 8 57 15 AM" src="https://github.com/nighthawkcoders/teacher_portfolio/assets/111466888/1bc08f07-880a-47fd-8e4b-dbf28e95e81f">

[blog linkj](https://ekam.nighthawkcodingsociety.com/2023/12/21/mcqcorrections_IPYNB_2_.html)

**Comment by drewreed2005** [comment]
Period 1
Drew Reed
39/39

[Link to blog with screenshot](https://drewreed2005.github.io/dre2.0//2023/12/21/CB_MC_2015_Reflection.html#my-score)

**Comment by VishnuAravind12** [comment]
Period 1
Vishnu Aravind
38/39 Score

[Link to my Blog Post](https://vishnuaravind12.github.io/vishnu/2023/12/21/CB_Reflection_v2.html)

**Comment by kaiden-dough** [comment]
Period 1
Kaiden Do
35/39

[Link](https://kaiden-dough.github.io/kaidencsablog/2023/12/20/collegeboardtest.html)

**Comment by vardaansinha** [comment]
Period 1
Vardaan Sinha
Score: 30/39

[Link to Blog](https://vardaansinha.github.io/vsstudent//2023/12/22/mcq_IPYNB_2_.html)

**Comment by aliyatang** [comment]
Period 1
Aliya Tang
39/39

[Link](https://aliyatang.github.io/aliyaBlog/posts/2015-MCQ/)

**Comment by vivianknee** [comment]
Per 1
Vivian Ni
32/39
[Link](https://vivianknee.github.io/vivianblog/posts/2015-mc/) to Blog

**Comment by Jyustin** [comment]
Per 1
Justin Nguyen 
29/39 (rip)
[link](https://jyustin.github.io/JN-CSAblog//c1.0/2023/12/21/csafinalmcq2.html)

**Comment by DasMoge124** [comment]
Period 1
Kevin Du
35/39
[Link](https://dasmoge124.github.io/student/c3.0/c3.1/c4.1/2023/12/22/Collegeboard-quiz.html)

**Comment by realethantran** [comment]
Period 1
Ethan Tran 
35/39
[Blog](https://ethan.nighthawkcodingsociety.com/2023/12/21/MCQ-Reflections_IPYNB_2_.html)

**Comment by TayKimmy** [comment]
Period 1
Tay Kim
34/39
[Link](https://taykimmy.github.io/CSA-Repository/2023/12/21/Collegeboard-Quiz_IPYNB_2_.html)

**Comment by dolphinalt** [comment]
Period 1
Ethan Zhao
31/39
[Link](https://github.com/dolphinalt/APCSA-Pages/issues/7)

**Comment by h4seeb-cmd** [comment]
‼️‼️‼️‼️ Work In Progress ‼️‼️‼️‼️

**Comment by raunak2007** [comment]
Per 1
Raunak Mondal
36/39
[link](https://raunak2007.github.io/csa-pages/2023/12/21/MC-2015-Blog.html)

**Comment by isabelle926** [comment]
Per 1 
Isabelle Gunawan
29/39 
[Link](https://github.com/isabelle926/isabelleTri2/blob/main/_posts/MC_Corrections.md)

**Comment by sreejagangapuram** [comment]
Period 1 
Sreeja Gangapuram 
18/39
[Link](https://github.com/sreejagangapuram/sreejagangg/issues/1)

**Comment by hsinaDitaM** [comment]
Period 3
Mati Danish
31/39
[Blog](https://hsinaditam.github.io/CSA_Notes/2015-csa-exam)

**Comment by Emaad-Mir** [comment]
Period 1
Emaad Mir
36/39
[Link](https://emaad-mir.github.io/emaad-github-pages1/2023/12/21/MC-2015-Blog.html)

**Comment by VINERAJ** [comment]
Period 3
Vinay Rajagopalan
28/39
[Link](https://vineraj.github.io/CSAblog2.0/2023/12/19/MCNotesTri2_IPYNB_2_.html)

**Comment by Soham360** [comment]
Period 3
Soham Kamat
36/39
[Link](https://soham360.github.io/APCSA//2023/11/05/MCQ2015-Reflection.html)

**Comment by tanayp327** [comment]
Period 3
Tanay Patel
34/39
[Link](https://tanayp327.github.io/bloggy/2023/12/21/CBquiz.html)

**Comment by raymondYsheng** [comment]
Period 3
Raymond Sheng
36/39
[Link](https://raymondysheng.github.io/CSA_Repo//2023/12/18/2015-Practice-Exam_IPYNB_2_.html)

**Comment by nVarap** [comment]
Period 3
Varaprasad Nibhanypudi
38/39
[Link](https://nvarap.github.io/CSABlog/2023/12/21/CBMCQ2015_IPYNB_2_.html)

**Comment by Ishi-Singh** [comment]
Period 3
Ishi Singh
29/39
[Link](https://ishi-singh.github.io/AP-CSA/2023/12/21/CollegeboardMCQ.html)

**Comment by EdwinKuttappi** [comment]
Period 3
Edwin Abraham
31/39
[Link](https://edwinkuttappi.github.io/CSABlog/2023/12/21/CB-MCQ-2_IPYNB_2_.html)

**Comment by Krishiv111** [comment]
Period 3
Krishiv Mahendru
27/39
[Link](https://github.com/Krishiv111/liverpoolkm3/issues/6)

**Comment by Toby-Leeder** [comment]
Period 3
Toby Leeder
37/39
[Link](https://toby-leeder.github.io/CSABlog/2023/12/21/collegeboardTest_IPYNB_2_.html)

**Comment by paravsalaniwal** [comment]
Period 3
Parav Salaniwal
33/39
[Link](https://paravsalaniwal.github.io/praopersonal/2015mcqblog)

**Comment by JasoXDDD** [comment]
Period 3
Haoxuan Tong
33/39
[link to blog](https://github.com/JasoXDDD/APCSA/issues/8)

**Comment by TheoH32** [comment]
Period 3
Theo Huntalas
21/39
[Blog](https://theoh32.github.io/csa_blog/2023/12/22/MC-Reflection.html)

**Comment by JishnuS420** [comment]
Period 1 
Jishnu Singiresu 
30/39
![MC Blog](https://jishnus420.github.io/BlogCSA/2023/12/22/MCBlog_IPYNB_2_.html)

**Comment by e-shen2022** [comment]
Period 1 
Emma Shen 
35/39
[MC Blog](https://github.com/e-shen2022/APCS_Blog/issues/61)

**Comment by BobTheFarmer** [comment]
Period 1 
Colin Weis
35/39
[Blog](url)

**Comment by gwang1224** [comment]
Period 1
Grace Wang
27/39
[Blog](https://gwang1224.github.io/Graces-Blog/2023/12/22/2014exam_IPYNB_2_.html)

**Comment by aidenhuynh** [comment]
Period 3
Aiden Huynh
32/39
[Blogging](https://aidenhuynh.github.io/Epic_CSA/2023/12/21/MCQ_2015_IPYNB_2_.html)

**Comment by AniCricKet** [comment]
Period 3
Aniket Chakradeo
[Blog]()

**Comment by Pitsco** [comment]
Period 3
Derrick Huang
Score: 29/39
[Blog](https://pitsco.github.io/personal/c4.0/2023/12/22/CB-2015-quiz-notes.html)

**Comment by YLu-1258** [comment]
Period 3
Alexander Lu
Score: 34/39
[Blog](https://ylu-1258.github.io/YLU_blog/posts/Collegeboard-MCQ-2015/)

**Comment by rachit-j** [comment]
Period 3
Rachit Jaiswal
35/39
[Blog](https://rachit-j.github.io/Rackets-Blog/2023/12/22/2015-MCQ-Reflection.html)

**Comment by lunaiwa** [comment]
Period 3
Luna Iwazaki
32/39
[Blog](https://lunaiwa.github.io/student-template//2023/12/22/CBCorr_IPYNB_2_.html)

**Comment by Orlando-c** [comment]
Period 3
Orlando Carcamo
[Link]()

**Comment by tanishapatil1234** [comment]
Period 3
Tanisha Patil
[Link](https://github.com/nighthawkcoders/teacher_portfolio/issues/55)

**Comment by F1nnC** [comment]
Period 1
Finn Carpenter
32/39
(link)[https://f1nnc.github.io/stud/MCQ2]

**Comment by Firestorm0986** [comment]
Period 3
Aditya Ajay Nawandhar
34/39
[link](url)

**Comment by Henerystone** [comment]
Period 3
Shreyas Sarurkar
33/39
https://henerystone.github.io/repo//2023/12/22/quiz_blog2.html
