### ISSUE TITLE
2020 CB MCQ - CSP

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/teacher_portfolio#56]
Add the following.

Period
Name
Score
Link to 5 minute blog

**Comment by LincolnC2008** [comment]
Period 2
Lincoln Crowell
51/67
https://lincolnc2008.github.io/student3//2023/12/20/CB-MC_IPYNB_2_.html

**Comment by iKAN2025** [comment]
Isabel Marilla
Period 2
Score: 61/67
https://ikan2025.github.io/Nighthawk-Pages//2023/12/16/CollegeBoard_IPYNB_2_.html

**Comment by Gurbop** [comment]
Gurshawn Boparai 
Period 2
59/67
https://gurbop.github.io/CSPBlog2//2023/12/21/cb2.html

**Comment by tuckergol** [comment]
Period 2
Tucker Golpariani
52/67
[https://tuckergol.github.io/student2//2023/12/21/MCQ_Reflection_IPYNB_2_.html](https://tuckergol.github.io/student2//2023/12/21/MCQ_Reflection_IPYNB_2_.html)

**Comment by DanteA-tech** [comment]
Period 2
Dante Atanassov
54/67
https://dantea-tech.github.io/student/2023/12/21/College-Board_IPYNB_2_.html

**Comment by sergi1207** [comment]
Period 2 
Sergi Serpukhovitinov
49/67
https://jm1021.github.io/sergiStudent//2023/12/21/Collegeboard-quiz-2020.html

**Comment by trevorhuang1** [comment]
Period 2
Trevor Huang
62/67
https://trevorhuang1.github.io/csp_blog/2023/12/21/CollegeBoardQuiz.html

**Comment by lakshusan** [comment]
Period 2
Lakshanya Sankaran
60/67
https://lakshusan.github.io/student2//2023/12/20/cb-practice-mcq-2020.html

**Comment by Flying-Book** [comment]
period 2
Anusha Khobare
64/67
https://flying-book.github.io/flyingbook_home_repo/

**Comment by DavidL0914** [comment]
Period 2
David Lee
62/67
https://davidl0914.github.io/student//2023/12/22/Test_blog_IPYNB_2_.html

**Comment by IshanCornick** [comment]
Period 2
Ishan Cornick
50/67
https://ishancornick.github.io/new_student//2023/12/21/review-ticket-corrections.html

**Comment by ak146** [comment]
Period 2
Andrew Kim
63/67
https://ak146.github.io/FunnyBlog2.0//2023/11/21/CSP-Quiz-2_IPYNB_2_.html

**Comment by vibha-yganji** [comment]
Period 2
Vibha Ganji
59/67
https://jplip.github.io/frontTri2/corrections/

**Comment by ad1tyad3sa1** [comment]
Period 2
Aditya Desai
57/67
https://ad1tyad3sa1.github.io/adityadesai2.0//2023/12/21/PersonalBlog.html

**Comment by Th35py27** [comment]
Period 2 
Nandan Vallamkondu
54/67
https://th35py27.github.io/CSP//2023/12/22/Collegeboard-MCQ.html

**Comment by peytonl11098** [comment]
Period 2
Peyton Leigh
Score: 62/67
https://peytonl11098.github.io/Ultron/2023/12/21/College_Board_Blog.html

**Comment by ellierozen** [comment]
Period 4
Ellie Rozenkrants
Score: 62/67
https://ellierozen.github.io/csp3-repo/2023/12/22/cb-2020-mc_IPYNB_2_.html

**Comment by YeongsuKimm** [comment]
Period 5
Yeongsu Kim
Score 62/67
https://yeongsukimm.github.io/yeongsuk//2023/12/21/collegeBoard_IPYNB_2_.html

**Comment by ShakeSphereStuff** [comment]
P5
Gavin Dyke
49/67
https://shakespherestuff.github.io/CSP-2/c1.4/2023/11/03/What-I've-learned-through-the-HW's.html

**Comment by SriS126** [comment]
P5
Sri Surapaneni
57/67
https://sris126.github.io/student//2023/12/21/CollegeBoardMCQReflection_IPYNB_2_.md_IPYNB_2_.html

**Comment by spooketti** [comment]
P5
Jonathan Liu
56/67
https://spooketti.github.io/studentmodern//2023/12/22/CollegeBoardMCQ.html

**Comment by katelync05** [comment]
Period 4
Katelyn Chen
61/67
https://github.com/katelync05/student2.0/blob/main/_posts/2023-12-22-MCQ-Reflection.md

**Comment by anikabhatnagar20** [comment]
Period 2 
Anika Bhatnagar 
61/67 
https://anikabhatnagar20.github.io/anikabhatnagar20//2023/12/22/CB2_reflection.html

**Comment by ak146** [comment]
Period 2
Andrew Kim
64/67
https://ak146.github.io/FunnyBlog2.0//2023/11/21/CSP-Quiz-2_IPYNB_2_.html

**Comment by srivaidyas** [comment]
Period 4 
Sri Vaidyanathan S
61/67
https://srivaidyas.github.io/student2.0//2023/12/21/Test_Corrections_IPYNB_2_.html

**Comment by nitinsandiego** [comment]
Period 2
Nitin Balaji
61/67
https://nitinsandiego.github.io/student//2023/12/22/CSP-Practice-Test_IPYNB_2_.html

**Comment by aashrayr** [comment]
Period 1
Aashray Rajagopalan
58/67
https://aashrayr.github.io/student2//2023/12/22/cbquiz_IPYNB_2_.html

**Comment by Akhil353** [comment]
Period 1
Akhil Singamneni
64/67
https://akhil353.github.io/student//2023/12/22/cb-mcq-review.html

**Comment by monke7769** [comment]
Period 5
Hayden Chen
67/67
https://monke7769.github.io/copy1//2023/12/18/CollegeboardMCReflection_IPYNB_2_.html

**Comment by AdiBricks** [comment]
Period 5
Aditya Ramesh
60/67
https://docs.google.com/presentation/d/1JcPtKQDs3qvO3UzuQ7BCHAaNSqKpQZwY6XTftby6la4/edit#slide=id.g2646e096fb3_0_12

Not at home rn, and having trouble commiting through another computer. Slides link provided till I get the chance to fix it.

**Comment by BearytheGreenBear** [comment]
Period 1
Kyle Liang
64/67
https://bearythegreenbear.github.io/csp-blog//2023/12/21/2020-Prctice-MCQ.html

**Comment by alaraipek** [comment]
Period 2
Alara Ipek
49/67
https://alaraipek.github.io/student//2023/12/22/CollegeBoardQuiz.html

**Comment by varunm532** [comment]
Period 2
Varun Manoj pillai
52/67
https://varunm532.github.io/varun2//2023/12/22/Collegeboard_2020_practicetest1.html

**Comment by beijanm** [comment]
Period 4
Beijan Moniza
61/67
https://beijanm.github.io/beijan.web//2023/12/22/collegeboardmcq_IPYNB_2_.html

**Comment by M8tth3** [comment]
Period 2
Matthew Wakayama
62/67
https://m8tth3.github.io/m8th3_2.0//2023/12/22/Corrections.html

**Comment by jplip** [comment]
Period 2
Justin Liporada
62/67
https://jplip.github.io/justin2.0//2023/12/22/College_Board_Reflection.html

**Comment by alishahussain** [comment]
Period 2
Alisha Hussain
55/67
https://alishahussain.github.io/student2//2023/12/22/mcreflection_IPYNB_2_.html

**Comment by SrijDude3416** [comment]
Period 5
Srijan Atti
62/67
[https://srijdude3416.github.io/student/2023/12/22/CollegeBoard-MC-2020-Reflection_IPYNB_2_.html](https://srijdude3416.github.io/student/2023/12/22/CollegeBoard-MC-2020-Reflection_IPYNB_2_.html)

**Comment by RonitT1234** [comment]
Period 1 
Ronit Thomas 
58/67
https://ronitt1234.github.io/CSP_BLOG_RT//2023/11/04/Collegeboard.html

**Comment by 7mwang** [comment]
Period 2
Matthew Wang
52/67
https://7mwang.github.io/matthew-wang/reflection

**Comment by Ashwinv93** [comment]
Period 2
Ashwin Visvanath
55/67
[https://ashwinv93.github.io/CompSci//2023/12/21/Quiz-Review_IPYNB_2_.html](https://ashwinv93.github.io/CompSci//2023/12/21/Quiz-Review_IPYNB_2_.html)

**Comment by Djxnxnx** [comment]
Period 1
Tarun Tata
61/67
https://djxnxnx.github.io/student//2023/12/23/CollegeBoardQuizReflection_IPYNB_2_.html

**Comment by Imaad08** [comment]
Period 1
Imaad Muzaffer
59/67
https://imaad08.github.io/student2//2023/12/22/CBReview.html

**Comment by SGTech08** [comment]
Period 2
Saathvik Gampa
64/67
https://sgtech08.github.io/student//2023/12/22/correction-for-collegeboard_IPYNB_2_.html

**Comment by AkshayNagesh** [comment]
Period 2 
Akshay Nagesh
59/67
https://akshaynagesh.github.io/student//2023/12/22/Practice-test.html

**Comment by sharonkodali** [comment]
Period 2 
Sharon kodali
52/67
https://sharonkodali.github.io/sharonk//2023/12/22/cs-test-blog_IPYNB_2_.html

**Comment by AnvayYadav** [comment]
Period 2
Anvay Yadav
60/67
https://anvayyadav.github.io/student//2023/12/22/2020cbcorrections_IPYNB_2_.html

**Comment by Lin-cT** [comment]
Period 5
Lindsay Tang
65/67
https://github.com/Lin-cT/stu2/blob/main/_notebooks/2023-12-22-Reflection_Collegeboard_MC.ipynb

**Comment by samhita-l** [comment]
Period 5
Samhita Lagisetti
63/67
https://samhita-l.github.io/compsci/2023/12/22/CBReflection_IPYNB_2_.html

**Comment by rliao569** [comment]
Period 1 Lopez 
Ryan Liao 
57/67
https://rliao569.github.io/Ryan-Blog-theREAL//5.a/c4.1/2023/12/22/mcqpractice2_IPYNB_2_.html

**Comment by JoshThinh** [comment]
Period 4 Lopez
Joshua Thinh
64/67
[https://joshthinh.github.io/T2joshua//2023/08/21/testcorrections_IPYNB_2_.html](https://joshthinh.github.io/T2joshua//2023/08/21/testcorrections_IPYNB_2_.html)

**Comment by dino596** [comment]
Period 4 Lopez
Arthur Liu
64/67
https://dino596.github.io/t2csp/2023/12/21/College_Board_MCQ_Review_IPYNB_2_.html

**Comment by sumedhaKl** [comment]
Period 4
Sumedha Kamaraju
35/67
http://127.0.0.1:4200/student/2023/12/22/5MinuteBlogCorrections.html

**Comment by jntpham** [comment]
Period 4
Jordan Pham
61/67
https://jntpham.github.io/jphamblog//2023/12/21/MCQ2_IPYNB_2_.html

**Comment by tarasehdave** [comment]
Period 2 Mortensen 
Tara Sehdave 
58/67
https://tarasehdave.github.io//c4.1/2023/12/22/MC2020Corrections_IPYNB_2_.html

**Comment by AidanLau10** [comment]
Period 1 Lopez
Aidan Lau
62/67
https://aidanlau10.github.io/student2//2023/12/22/mcq_IPYNB_2_.html

**Comment by Tanvi-3** [comment]
Period 5: Lopez
Tanvi Pampati
64/67
http://127.0.0.1:4200/tanvipampati3//2023/12/23/cbcorrections_IPYNB_2_.html

**Comment by nikkihekmat** [comment]
Period 4: Lopez
Nikki Hekmat
http://127.0.0.1:4100/nikki-2.0//2023/12/20/2020MCQ_IPYNB_2_.html

**Comment by eunseolim123** [comment]
Period 4 Lopez
Eunseo Lim
62/67
https://eunseolim123.github.io/student-2.0/2023/12/21/Practice_MC_Blog_IPYNB_2_.html

**Comment by jkaeshim** [comment]
Period 4 Lopez
Jake Shim
56/67
https://github.com/jkaeshim/student/blob/main/_notebooks/2023-12-21-CollegeBoardReview2020.ipynb

**Comment by JasonGao76** [comment]
Period 5 Lopez
Jason Gao
63/67
https://jasongao76.github.io/students//2023/12/17/CB_MC_Notes.html

**Comment by TimoA35** [comment]
Period 4 Lopez
Tim Al-Faraje
61/67
Link to 5 minute blog: https://github.com/TimoA35/studentrepo/blob/main/_posts/2023-12-22-collegeboardmcq.ipynb

**Comment by eshaank1** [comment]
Period 1 Lopez
Eshaan Kumar
56/67
https://eshaank1.github.io/csp//2023/12/22/CollegeBoardQuizPlan_IPYNB_2_.html

**Comment by RyanZLiu** [comment]
Period 5 Lopez
Ryan Liu
Score: 67/67
https://ryanzliu.github.io/student4/2023/12/21/cbreview.html

(I was gone from Friday to this evening with an excused absence on Friday so I didn't see the announcement in slack and thus couldn't submit my collegeboard mc review ticket)

**Comment by anaghaa1206** [comment]
Period 1 Lopez
Anagha Ashtewale
64/67
https://anaghaa1206.github.io/anagha12//2023/12/29/quiz_blog.html

**Comment by RayyanDarugar** [comment]
Period 5
Rayyan Darugar
63/67
https://rayyandarugar.github.io/student//2023/12/22/CollegeboardMC2020_Review_IPYNB_2_.html

**Comment by iwu78** [comment]
Period 5
Ian Wu
66/67
https://iwu78.github.io/csp-blog//log/2023/12/27/Quiz-Reflection.html

**Comment by AdityaSamavedam** [comment]
Period 5
Aditya Samavedam
54/67
https://adityasamavedam.github.io/student2//2023/12/17/CB-5-min-blog.html

**Comment by Tanuj253** [comment]
Period 2
Tanujsai Nimmagadda
49/67
https://tanuj253.github.io/student2.0//2023/12/20/quiz_corrections_IPYNB_2_.html

**Comment by AaronH1234** [comment]
Period 1

**Comment by isabellehp** [comment]
Period 1
Isabelle Park
57/67
https://isabellehp.github.io/isabelle2//2023/12/20/CB-MCQ.html

**Comment by SrinivasNampalli** [comment]
Period 1
Srinivas Nampalli
59/67
https://github.com/SrinivasNampalli/Srinivas-Nampalli1/issues/2

**Comment by tarunja1ks** [comment]
Period 5
Tarun Jaikumar
60/67
https://tarunja1ks.github.io/student//2023/12/18/collegeboardreview_IPYNB_2_.html

**Comment by tanav-kambhampati** [comment]
Period 1
Tanav Kambhampati 
60/67
https://tanav-kambhampati.github.io/student2//2024/01/08/CB_Quiz_IPYNB_2_.html

**Comment by VanceReynolds** [comment]
Period 2
Vance Reynolds
62/67
https://vancereynolds.github.io/cspblog2//2023/01/08/2020_CB_MCQ.html

**Comment by Deeskili** [comment]
Period 4
Cayden Shi 
64/67
https://deeskili.github.io/student//2023/12/19/secondmcqcsp_IPYNB_2_.html

**Comment by cliang1** [comment]
57/67
Cindy Liang Per 5 Lopez
https://cliang1.github.io/cliang//2023/12/20/Test-Corrections_IPYNB_2_.html

**Comment by JasonGuan1012** [comment]
Period 1
Jason Guan
44/67
https://github.com/JasonGuan1012/student/blob/main/_notebooks/2023-12-30-MCQReflection.ipynb

**Comment by saiseahawks** [comment]
Period 5
Sai Talisetty
64/67
https://saiseahawks.github.io/student/2023/12/15/Quiz_Reflection_IPYNB_2_.html

**Comment by eashaan-r** [comment]
Period 1 
Eashaan Reddy
64/67
https://github.com/eashaan-r/eashaansite/blob/main/_posts/2024-01-01-MCReflection.md
(website not working currently)

**Comment by jaydenchen17** [comment]
Period 1
Jayden Chen
56/67
https://jaydenchen17.github.io/csp/2023/12/21/CB2020MCQ-practice_IPYNB_2_.html

**Comment by KaydenLe** [comment]
Period 2
Kayden Le
63/67
https://kaydenle.github.io/student3//2023/01/09/CB_2020.html

**Comment by MiguelVilla1** [comment]
Period 1
Miguel Villa-Hernandez
53/67

https://miguelvilla1.github.io/stewie/2024/01/08/CollegeboardQuizReflection_IPYNB_2_.html

**Comment by will-w-cheng** [comment]
Period 5 Lopez
William Cheng
64/67 

https://will-w-cheng.github.io/student-public//2023/12/22/Quiz-Corrections_IPYNB_2_.html

**Comment by Marcushe31** [comment]
Period 1
Marcus Hernandez
61/67
https://marcushe31.github.io/MARCUS/

**Comment by hanlunli** [comment]
Period 2
Hanlun Li
60/67

https://hanlunli.github.io/student/2023/01/08/CB-Reflection_IPYNB_2_.html

**Comment by abdullahkhanani9** [comment]
Period 2
Abdullah Khanani
43/67
https://abdullahkhanani9.github.io/abdullahrepository2//2023/12/21/collegeboardtest2.html

**Comment by JBaza12** [comment]
Jared Baza
Period 4
64/67
https://jbaza12.github.io/JaredsBlog//2024/01/09/CBTC_IPYNB_2_.html

**Comment by AustinZhang1** [comment]
Period 4

**Comment by AustinZhang1** [comment]
Austin Zhang
Period 4
65/67
https://github.com/AustinZhang1/student/blob/main/_notebooks/2023-12-20-Collegeboard-mcq.ipynb
